services:
  database:
    image: postgres:latest
    container_name: appliance_registry_db
    environment:
      POSTGRES_USER: silent_rider
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appliance_registry
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appliance_registry_network
  
  server:
    build:
      context: ./
    container_name: appliance_registry_server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/appliance_registry
      SPRING_DATASOURCE_USERNAME: silent_rider
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - appliance_registry_network

networks:
  appliance_registry_network:

volumes:
  db_data:
